# Generated by Django 5.2.2 on 2025-06-04 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('social_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Social')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('rg_issue_date', models.DateField(blank=True, null=True, verbose_name='Data de Emissão RG')),
                ('rg_issuer', models.CharField(blank=True, max_length=50, null=True, verbose_name='Órgão Emissor RG')),
                ('phone_whatsapp', models.CharField(max_length=20, verbose_name='Telefone com WhatsApp')),
                ('address_street', models.CharField(max_length=255, verbose_name='Rua')),
                ('address_number', models.CharField(max_length=20, verbose_name='Número')),
                ('address_complement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('address_neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('address_city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('address_state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado')),
                ('address_zip', models.CharField(max_length=9, verbose_name='CEP')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cvs/', verbose_name='Currículo (CV)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do Candidato',
                'verbose_name_plural': 'Perfis dos Candidatos',
            },
        ),
        migrations.CreateModel(
            name='ComplementaryCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255, verbose_name='Nome do Curso')),
                ('institution', models.CharField(max_length=255, verbose_name='Instituição')),
                ('duration_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Carga Horária (horas)')),
                ('completion_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano de Realização')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complementary_courses', to='accounts.candidateprofile')),
            ],
            options={
                'verbose_name': 'Curso Complementar',
                'verbose_name_plural': 'Cursos Complementares',
                'ordering': ['-completion_year'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('FUND_INC', 'Ensino Fundamental Incompleto'), ('FUND_COMP', 'Ensino Fundamental Completo'), ('MED_INC', 'Ensino Médio Incompleto'), ('MED_COMP', 'Ensino Médio Completo'), ('SUP_INC', 'Superior Incompleto'), ('SUP_COMP', 'Superior Completo'), ('POS', 'Pós-graduação'), ('MEST', 'Mestrado'), ('DOUT', 'Doutorado')], max_length=10, verbose_name='Nível de Escolaridade')),
                ('course', models.CharField(blank=True, max_length=255, null=True, verbose_name='Curso')),
                ('institution', models.CharField(max_length=255, verbose_name='Instituição de Ensino')),
                ('conclusion_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano de Conclusão')),
                ('status', models.CharField(choices=[('COMPLETO', 'Completo'), ('CURSANDO', 'Cursando'), ('INCOMPLETO', 'Incompleto')], default='COMPLETO', max_length=10, verbose_name='Status')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_history', to='accounts.candidateprofile')),
            ],
            options={
                'verbose_name': 'Formação Acadêmica',
                'verbose_name_plural': 'Formações Acadêmicas',
                'ordering': ['-conclusion_year'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255, verbose_name='Cargo')),
                ('company', models.CharField(max_length=255, verbose_name='Empresa')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('responsibilities', models.TextField(blank=True, null=True, verbose_name='Principais Atividades/Responsabilidades')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='accounts.candidateprofile')),
            ],
            options={
                'verbose_name': 'Experiência Profissional',
                'verbose_name_plural': 'Experiências Profissionais',
                'ordering': ['-start_date'],
            },
        ),
    ]
