# Generated by Django 5.2.2 on 2025-06-04 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobVacancyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome do Tipo de Vaga')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('field_config', models.JSONField(default=dict, help_text='Estrutura JSON definindo os campos e suas propriedades (visibilidade, obrigatoriedade, etc.) para este tipo de vaga.', verbose_name='Configuração de Campos do Formulário')),
            ],
            options={
                'verbose_name': 'Tipo de Vaga',
                'verbose_name_plural': 'Tipos de Vaga',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True, verbose_name='Data da Candidatura')),
                ('status', models.CharField(choices=[('RECEIVED', 'Recebida'), ('SCREENING', 'Triagem'), ('INTERVIEW', 'Entrevista'), ('TEST', 'Teste'), ('OFFER', 'Oferta'), ('HIRED', 'Contratado'), ('REJECTED', 'Rejeitado'), ('CANCELED', 'Cancelada')], default='RECEIVED', max_length=15, verbose_name='Status da Candidatura')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Score (Triagem)')),
                ('recruiter_notes', models.TextField(blank=True, null=True, verbose_name='Notas do Recrutador')),
                ('submitted_data', models.JSONField(default=dict, verbose_name='Dados Submetidos na Candidatura')),
                ('pcd_medical_report_file', models.FileField(blank=True, null=True, upload_to='laudos/', verbose_name='Laudo Médico PCD')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.candidateprofile', verbose_name='Candidato')),
            ],
            options={
                'verbose_name': 'Candidatura',
                'verbose_name_plural': 'Candidaturas',
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField(verbose_name='Data/Hora Agendada')),
                ('interview_type', models.CharField(blank=True, help_text='Ex: Triagem RH, Técnica, Gestor', max_length=100, null=True, verbose_name='Tipo de Entrevista')),
                ('location_details', models.TextField(blank=True, help_text='Ex: Link da videochamada, Sala X', null=True, verbose_name='Detalhes/Localização')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Agendada'), ('COMPLETED', 'Realizada'), ('CANCELED', 'Cancelada'), ('RESCHEDULED', 'Reagendada'), ('NO_SHOW', 'Não Compareceu')], default='SCHEDULED', max_length=15, verbose_name='Status')),
                ('recruiter_feedback', models.TextField(blank=True, null=True, verbose_name='Feedback do Entrevistador')),
                ('candidate_feedback', models.TextField(blank=True, null=True, verbose_name='Feedback do Candidato')),
                ('interviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_interviews', to=settings.AUTH_USER_MODEL, verbose_name='Entrevistador')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='vacancies.jobapplication', verbose_name='Candidatura')),
            ],
            options={
                'verbose_name': 'Entrevista',
                'verbose_name_plural': 'Entrevistas',
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título da Vaga')),
                ('description', models.TextField(verbose_name='Descrição Detalhada')),
                ('requirements', models.TextField(verbose_name='Requisitos')),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True, verbose_name='Faixa Salarial')),
                ('status', models.CharField(choices=[('OPEN', 'Aberta'), ('CLOSED', 'Fechada'), ('FILLED', 'Preenchida')], default='OPEN', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vacancies', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='core.department', verbose_name='Setor')),
                ('hospital_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancies', to='core.hospitalunit', verbose_name='Unidade Hospitalar')),
                ('vacancy_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancies', to='vacancies.jobvacancytype', verbose_name='Tipo de Vaga')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='vacancies.jobvacancy', verbose_name='Vaga'),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('candidate', 'job_vacancy')},
        ),
    ]
