# Generated by Django 5.2.2 on 2025-06-04 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('vacancies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(help_text='Ex: candidatou-se, atualizou_status, agendou_entrevista, criou_vaga', max_length=255, verbose_name='Ação')),
                ('details', models.JSONField(blank=True, help_text='Ex: status antigo/novo, detalhes da entrevista', null=True, verbose_name='Detalhes Adicionais')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to=settings.AUTH_USER_MODEL, verbose_name='Ator')),
                ('target_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='vacancies.jobapplication', verbose_name='Candidatura Alvo')),
                ('target_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='accounts.candidateprofile', verbose_name='Candidato Alvo')),
                ('target_vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='vacancies.jobvacancy', verbose_name='Vaga Alvo')),
            ],
            options={
                'verbose_name': 'Registro de Atividade',
                'verbose_name_plural': 'Registros de Atividade',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('notification_type', models.CharField(choices=[('STATUS_UPDATE', 'Atualização de Status'), ('INTERVIEW_SCHEDULED', 'Entrevista Agendada'), ('NEW_VACANCY', 'Nova Vaga Correspondente'), ('APPLICATION_RECEIVED', 'Candidatura Recebida'), ('GENERAL', 'Geral')], default='GENERAL', max_length=30, verbose_name='Tipo de Notificação')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário')),
                ('related_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='vacancies.jobapplication', verbose_name='Candidatura Relacionada')),
                ('related_vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='vacancies.jobvacancy', verbose_name='Vaga Relacionada')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
            },
        ),
    ]
